# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApproxFindbyNameInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, preferred_term: str=None):  # noqa: E501
        """ApproxFindbyNameInner - a model defined in Swagger

        :param _date: The _date of this ApproxFindbyNameInner.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this ApproxFindbyNameInner.  # noqa: E501
        :type orph_acode: int
        :param preferred_term: The preferred_term of this ApproxFindbyNameInner.  # noqa: E501
        :type preferred_term: str
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'preferred_term': str
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'preferred_term': 'Preferred term'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._preferred_term = preferred_term

    @classmethod
    def from_dict(cls, dikt) -> 'ApproxFindbyNameInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApproxFindbyName_inner of this ApproxFindbyNameInner.  # noqa: E501
        :rtype: ApproxFindbyNameInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this ApproxFindbyNameInner.


        :return: The _date of this ApproxFindbyNameInner.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this ApproxFindbyNameInner.


        :param _date: The _date of this ApproxFindbyNameInner.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this ApproxFindbyNameInner.


        :return: The orph_acode of this ApproxFindbyNameInner.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this ApproxFindbyNameInner.


        :param orph_acode: The orph_acode of this ApproxFindbyNameInner.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def preferred_term(self) -> str:
        """Gets the preferred_term of this ApproxFindbyNameInner.


        :return: The preferred_term of this ApproxFindbyNameInner.
        :rtype: str
        """
        return self._preferred_term

    @preferred_term.setter
    def preferred_term(self, preferred_term: str):
        """Sets the preferred_term of this ApproxFindbyNameInner.


        :param preferred_term: The preferred_term of this ApproxFindbyNameInner.
        :type preferred_term: str
        """

        self._preferred_term = preferred_term
