# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.findby_omim_references import FindbyOMIMReferences  # noqa: F401,E501
from swagger_server import util


class FindbyOMIM(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, code_omim: int=None, references: List[FindbyOMIMReferences]=None):  # noqa: E501
        """FindbyOMIM - a model defined in Swagger

        :param _date: The _date of this FindbyOMIM.  # noqa: E501
        :type _date: datetime
        :param code_omim: The code_omim of this FindbyOMIM.  # noqa: E501
        :type code_omim: int
        :param references: The references of this FindbyOMIM.  # noqa: E501
        :type references: List[FindbyOMIMReferences]
        """
        self.swagger_types = {
            '_date': datetime,
            'code_omim': int,
            'references': List[FindbyOMIMReferences]
        }

        self.attribute_map = {
            '_date': 'Date',
            'code_omim': 'Code OMIM',
            'references': 'References'
        }
        self.__date = _date
        self._code_omim = code_omim
        self._references = references

    @classmethod
    def from_dict(cls, dikt) -> 'FindbyOMIM':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindbyOMIM of this FindbyOMIM.  # noqa: E501
        :rtype: FindbyOMIM
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this FindbyOMIM.


        :return: The _date of this FindbyOMIM.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this FindbyOMIM.


        :param _date: The _date of this FindbyOMIM.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def code_omim(self) -> int:
        """Gets the code_omim of this FindbyOMIM.


        :return: The code_omim of this FindbyOMIM.
        :rtype: int
        """
        return self._code_omim

    @code_omim.setter
    def code_omim(self, code_omim: int):
        """Sets the code_omim of this FindbyOMIM.


        :param code_omim: The code_omim of this FindbyOMIM.
        :type code_omim: int
        """

        self._code_omim = code_omim

    @property
    def references(self) -> List[FindbyOMIMReferences]:
        """Gets the references of this FindbyOMIM.


        :return: The references of this FindbyOMIM.
        :rtype: List[FindbyOMIMReferences]
        """
        return self._references

    @references.setter
    def references(self, references: List[FindbyOMIMReferences]):
        """Sets the references of this FindbyOMIM.


        :param references: The references of this FindbyOMIM.
        :type references: List[FindbyOMIMReferences]
        """

        self._references = references
