# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrphanetURL(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, orphanet_url: str=None):  # noqa: E501
        """OrphanetURL - a model defined in Swagger

        :param _date: The _date of this OrphanetURL.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this OrphanetURL.  # noqa: E501
        :type orph_acode: int
        :param orphanet_url: The orphanet_url of this OrphanetURL.  # noqa: E501
        :type orphanet_url: str
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'orphanet_url': str
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'orphanet_url': 'OrphanetURL'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._orphanet_url = orphanet_url

    @classmethod
    def from_dict(cls, dikt) -> 'OrphanetURL':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrphanetURL of this OrphanetURL.  # noqa: E501
        :rtype: OrphanetURL
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this OrphanetURL.


        :return: The _date of this OrphanetURL.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this OrphanetURL.


        :param _date: The _date of this OrphanetURL.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this OrphanetURL.


        :return: The orph_acode of this OrphanetURL.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this OrphanetURL.


        :param orph_acode: The orph_acode of this OrphanetURL.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def orphanet_url(self) -> str:
        """Gets the orphanet_url of this OrphanetURL.


        :return: The orphanet_url of this OrphanetURL.
        :rtype: str
        """
        return self._orphanet_url

    @orphanet_url.setter
    def orphanet_url(self, orphanet_url: str):
        """Sets the orphanet_url of this OrphanetURL.


        :param orphanet_url: The orphanet_url of this OrphanetURL.
        :type orphanet_url: str
        """

        self._orphanet_url = orphanet_url
