# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.parent_classification import ParentClassification  # noqa: F401,E501
from swagger_server.models.parent_parent import ParentParent  # noqa: F401,E501
from swagger_server import util


class Parent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, preferred_term: str=None, classification: ParentClassification=None, parent: List[ParentParent]=None):  # noqa: E501
        """Parent - a model defined in Swagger

        :param _date: The _date of this Parent.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this Parent.  # noqa: E501
        :type orph_acode: int
        :param preferred_term: The preferred_term of this Parent.  # noqa: E501
        :type preferred_term: str
        :param classification: The classification of this Parent.  # noqa: E501
        :type classification: ParentClassification
        :param parent: The parent of this Parent.  # noqa: E501
        :type parent: List[ParentParent]
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'preferred_term': str,
            'classification': ParentClassification,
            'parent': List[ParentParent]
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'preferred_term': 'Preferred term',
            'classification': 'Classification',
            'parent': 'Parent'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._preferred_term = preferred_term
        self._classification = classification
        self._parent = parent

    @classmethod
    def from_dict(cls, dikt) -> 'Parent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parent of this Parent.  # noqa: E501
        :rtype: Parent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this Parent.


        :return: The _date of this Parent.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this Parent.


        :param _date: The _date of this Parent.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this Parent.


        :return: The orph_acode of this Parent.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this Parent.


        :param orph_acode: The orph_acode of this Parent.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def preferred_term(self) -> str:
        """Gets the preferred_term of this Parent.


        :return: The preferred_term of this Parent.
        :rtype: str
        """
        return self._preferred_term

    @preferred_term.setter
    def preferred_term(self, preferred_term: str):
        """Sets the preferred_term of this Parent.


        :param preferred_term: The preferred_term of this Parent.
        :type preferred_term: str
        """

        self._preferred_term = preferred_term

    @property
    def classification(self) -> ParentClassification:
        """Gets the classification of this Parent.


        :return: The classification of this Parent.
        :rtype: ParentClassification
        """
        return self._classification

    @classification.setter
    def classification(self, classification: ParentClassification):
        """Sets the classification of this Parent.


        :param classification: The classification of this Parent.
        :type classification: ParentClassification
        """

        self._classification = classification

    @property
    def parent(self) -> List[ParentParent]:
        """Gets the parent of this Parent.


        :return: The parent of this Parent.
        :rtype: List[ParentParent]
        """
        return self._parent

    @parent.setter
    def parent(self, parent: List[ParentParent]):
        """Sets the parent of this Parent.


        :param parent: The parent of this Parent.
        :type parent: List[ParentParent]
        """

        self._parent = parent
