# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParentParent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orph_acode: int=None, preferred_term: str=None):  # noqa: E501
        """ParentParent - a model defined in Swagger

        :param orph_acode: The orph_acode of this ParentParent.  # noqa: E501
        :type orph_acode: int
        :param preferred_term: The preferred_term of this ParentParent.  # noqa: E501
        :type preferred_term: str
        """
        self.swagger_types = {
            'orph_acode': int,
            'preferred_term': str
        }

        self.attribute_map = {
            'orph_acode': 'ORPHAcode',
            'preferred_term': 'Preferred term'
        }
        self._orph_acode = orph_acode
        self._preferred_term = preferred_term

    @classmethod
    def from_dict(cls, dikt) -> 'ParentParent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parent_Parent of this ParentParent.  # noqa: E501
        :rtype: ParentParent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this ParentParent.


        :return: The orph_acode of this ParentParent.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this ParentParent.


        :param orph_acode: The orph_acode of this ParentParent.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def preferred_term(self) -> str:
        """Gets the preferred_term of this ParentParent.


        :return: The preferred_term of this ParentParent.
        :rtype: str
        """
        return self._preferred_term

    @preferred_term.setter
    def preferred_term(self, preferred_term: str):
        """Sets the preferred_term of this ParentParent.


        :param preferred_term: The preferred_term of this ParentParent.
        :type preferred_term: str
        """

        self._preferred_term = preferred_term
