# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Status(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, status: str=None):  # noqa: E501
        """Status - a model defined in Swagger

        :param _date: The _date of this Status.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this Status.  # noqa: E501
        :type orph_acode: int
        :param status: The status of this Status.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'status': str
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'status': 'Status'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Status':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Status of this Status.  # noqa: E501
        :rtype: Status
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this Status.


        :return: The _date of this Status.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this Status.


        :param _date: The _date of this Status.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this Status.


        :return: The orph_acode of this Status.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this Status.


        :param orph_acode: The orph_acode of this Status.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def status(self) -> str:
        """Gets the status of this Status.


        :return: The status of this Status.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Status.


        :param status: The status of this Status.
        :type status: str
        """
        allowed_values = ["Active", "Inactive: Non rare disease in Europe", "Inactive: Obsolete", "Inactive: Deprecated"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
