# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Synonym(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, synonym: List[str]=None):  # noqa: E501
        """Synonym - a model defined in Swagger

        :param _date: The _date of this Synonym.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this Synonym.  # noqa: E501
        :type orph_acode: int
        :param synonym: The synonym of this Synonym.  # noqa: E501
        :type synonym: List[str]
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'synonym': List[str]
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'synonym': 'Synonym'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._synonym = synonym

    @classmethod
    def from_dict(cls, dikt) -> 'Synonym':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Synonym of this Synonym.  # noqa: E501
        :rtype: Synonym
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this Synonym.


        :return: The _date of this Synonym.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this Synonym.


        :param _date: The _date of this Synonym.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this Synonym.


        :return: The orph_acode of this Synonym.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this Synonym.


        :param orph_acode: The orph_acode of this Synonym.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def synonym(self) -> List[str]:
        """Gets the synonym of this Synonym.


        :return: The synonym of this Synonym.
        :rtype: List[str]
        """
        return self._synonym

    @synonym.setter
    def synonym(self, synonym: List[str]):
        """Sets the synonym of this Synonym.


        :param synonym: The synonym of this Synonym.
        :type synonym: List[str]
        """

        self._synonym = synonym
